### ISSUE TITLE
백엔드에서의 따닥막기

### ISSUE THREAD

**Issue by jaehyeong2** [geminiKim/development-practice#23]
안녕하세요 제미니님! 유튜브 잘보고있습니다

다름이 아니라, 따닥을 프론트 처리로만 막지 않고 이중으로 백단에서도 막고 싶은 상황일 때 어떤식으로 처리하는지 알 수 있을까요? 

프로세스가 1개일 때와, 여러 프로세스가 있을 때 두 상황에 대해서 알고 싶습니다.

- 1대이면 로컬캐시, 여러개면 글로벌 캐시
- 클라이언트에서 요청 시 unique한 트랜잭션 키값? 등 받기
정도가 생각나는데, 괜찮으시면 가르침을 바랍니다. 꾸벅

**Comment by geminiKim** [comment]
질문 감사드립니다! :D
추후에 얘기 해보도록 하겠습니다!

**Comment by geminiKim** [comment]
test

**Comment by geminiKim** [comment]
test

**Comment by geminiKim** [comment]
test

**Comment by geminiKim** [comment]
TEST

**Comment by geminiKim** [comment]
TEST

**Comment by geminiKim** [comment]
TEST

**Comment by geminiKim** [comment]
TEST

**Comment by geminiKim** [comment]
to: https://youtu.be/BYVUMu260Sw?feature=shared
