### ISSUE TITLE
git에서 형상관리 하시는 방법이 궁금합니다!

### ISSUE THREAD

**Issue by jay-choe** [geminiKim/development-practice#32]
큰 규모의 작업을 할 때 commit 해야 할 작업 task를 나누는 기준이 궁금합니다.

제가 생각하는 개발자들의 commit하는 방식은 크게 2가지로 나뉜다고 생각하는데
1. commit 할 작업 단위를 먼저 생각해보고 -> 그 단위로 작업을 하면서 중간중간 commit한다.
2. 그냥 한번에 기능 단위 개발을 하고 -> 이후에 작업을 쪼개면서 commit한다.

이중에 저는 두 번째 방식으로 작업하는 스타일입니다.

이때 느끼는 점은, 주로 큰 규모의 작업을 할 때 앞 뒤로 연관된 부분이 많아 중간중간 commit하지 않고 한 번에 개발하고
이후 버전 관리를 위해 task를 나누는데, 이 나누는 경계가 모호해지는 경우가 많습니다..

재민님은 어떤 과정으로 개발하면서 형상관리를 하시는지 궁금합니다.

**Comment by geminiKim** [comment]
질문 감사합니다! 차후에 다뤄보도록 하겠습니다!👍

**Comment by geminiKim** [comment]
to: https://youtu.be/su-rtXzThjE?si=cBOrAfyjpnyXUsrA
