### ISSUE TITLE
서비스 내에서 계층간 주고받는 DTO/VO는 어떻게 관리하는게 좋을까요?

### ISSUE THREAD

**Issue by Heekng** [geminiKim/development-practice#33]
안녕하세요. 재미니님 통해서 많은 도움 받고 있습니다. 항상 감사합니다!

서비스 개발할 떄, 각 계층간 여러 객체가 이동하게 되는데요.
운영되는 서비스 내에서 외부(프레젠테이션 레이어)에서 요청받는 객체(request) 와 응답하는 객체(response)를 나눈 상태이고, 프레젠테이션 레이어와 서비스 레이어 사이에서 또 하나의 DTO를 선언하여 주고받는 형태로 규칙을 정하여 개발하고 있습니다.
문제는 이 과정에서 굳이 진행하지 않아도 될 DTO간 매핑을 하는 상황이 나오게 되더라구요.
물론 팀 컨벤션 안에서 결정해야할 사항이지만, 이러한 계층 사이의 데이터를 주고받는 방법에 대해 재미니님의 생각이 궁금합니다.

**Comment by geminiKim** [comment]
질문 감사합니다! 차후에 다뤄보도록 하겠습니다!👍

**Comment by geminiKim** [comment]
to: https://youtu.be/Zs4VYXudYIQ?si=Jcp9tN984QWOM08W
