### ISSUE TITLE
올바른 성능테스트란 무엇일까요?

### ISSUE THREAD

**Issue by picbel** [geminiKim/development-practice#38]
영상을 잘 시청하고 있습니다. 
영상에서 자주 다루는 주제 중 하나인 성능 테스트에 대한 제미니님의 의견과 조언에 대해 궁금합니다. 
성능 테스트를 진행할 때, 제 개인적인 기준으로는 JMeter를 사용하여 트래픽을 조절하면서 테스트를 수행하고 있는 것 같습니다. 
이 과정에서 트래픽을 설정하는 데 어떤 팁이 있을까요? (영상에서는 현재 트래픽의 3배 정도로 언급하셨지만, 더 자세한 정보를 얻고 싶습니다.)

또한, 실무에서 성능 테스트를 적용하는 다른 방법이 있는지 알려주실 수 있을까요? 그리고 개발팀 내에서 성능 테스트를 문화로 자리잡게 하는 데 도움이 될만한 조언이 있다면 공유해 주시면 좋겠습니다.

**Comment by geminiKim** [comment]
질문 감사합니다! 추후에 얘기 해보겠습니다!

**Comment by geminiKim** [comment]
to: https://youtu.be/20dhBGPQ6aA?si=YOK0vDVdo0JD8OQh
