### ISSUE TITLE
모듈을 분리했을 때 모듈 간의 의존관계 설정에 관하여 질문이 있습니다.

### ISSUE THREAD

**Issue by hyunzxn** [geminiKim/development-practice#40]
안녕하세요! 저는 진행하고 있는 작은 프로젝트를 멀티모듈로 만들어 보는 시도를 하고 있는 취준생입니다. 

제가 생각하는 구성은 우선 core, admin-api, user-api 이렇게 세 가지로 시작을 해보려고 하고 있습니다. core 쪽에 도메인과 비즈니스, 구현 레이어, data-access-layer를 일단 다 넣어볼 생각입니다. 그리고 api 쪽에는 controller 와 request, response를 넣어볼 생각을 하고 있습니다. 

위와 같은 구조로 모듈을 분리해보면, api 쪽에서 `@RequestBody`로 받은 요청 객체를 비즈니스 레이어(Service)에 바로 넘기게 되면 core 쪽 모듈에서도 api 쪽 모듈을 의존하게 되는 문제가 발생하는 것 같습니다.

```java
// api 쪽 코드
@PostMapping("/signup")
public ApiResponse<Long> signup(@Valid @RequestBody Signup request) {
    long newMemberId = authService.append(request);
    return ApiResponse.of(HttpStatus.CREATED, "새로운 회원 추가가 완료되었습니다.", newMemberId);
}
```
```java
// core 쪽 코드 (현재 core 모듈이 api 모듈을 의존하지 않는 상황을 가정
public long append(Signup request) { // Signup 클래스를 모르기 때문에 컴파일 에러가 발생
    Member newMember = memberAppender.append(request);
    return newMember.getId();
}
```
근데 가급적 저는 api -> core는 되지만 core -> api는 의존하고 싶지 않게 하고 싶습니다. (이게 맞는 생각인지는 잘 모르겠습니다만..) 

가장 간단하게 생각해봤을 때 그냥 Signup 객체에 있는 값들을 하나하나 꺼내서 `authService.append()` 의 파라미터로 넘겨주면 될 거 같긴 한데, 그러면 컨트롤러 쪽 코드가 너무 복잡해질 것 같기도 하고 뭔가 더 좋은 방법이 없을까 하는 생각이 들기도 합니다.

혹시 이런 부분은 어떻게 해결하는 것이 좋은지 의견을 남겨주시면 감사하겠습니다.

그리고 재민님 유튜브 영상에서 예시로 코드를 보여주시면서 설명을 하실 때 컨트롤러 쪽에 `provider: Provider` 라는 파라미터를 메서드에 공통적으로 넣어주셨는데 Provider 클래스가 어떤 역할을 하는 지도 좀 궁금합니다!

멀티 모듈이라는 것을 처음 시도해보는 중이라 미숙한 점이 많아 질문이 장황한 점 죄송합니다 ㅠ

**Comment by geminiKim** [comment]
질문 감사합니다! 추후에 얘기 해보겠습니다!

**Comment by geminiKim** [comment]
to: https://youtu.be/nVGV8ag8v7g?si=N7zfhXlnZw9s3AEK
