### ISSUE TITLE
질문사항이 있어서 문의 드립니다.

### ISSUE THREAD

**Issue by hyunsu15** [geminiKim/development-practice#54]
안녕하세요. 제미니의 개발 실무 구독자입니다.

다름이 아니라, 궁금한 점이 있어서, 연락드렸습니다.

## 해당 문제는 프론트엔드에서 처리해야 하는지? 백엔드에서 처리해야 하는지 궁금합니다.

Response.java
```
int personTotalSize;
int sickPersonCount;
double sickPersonPercent; // << 이부분

```
저 부분은 아픈 사람의 퍼센트는 프론트엔드에서 충분히 구할 수 있는 부분이라고 생각했습니다. 그래서 프론트엔드에서 처리하는 것이 맞다고 생각했었습니다. 하지만, ios나 aos등까지 이 요구사항이 필요하다면, 백엔드가 처리해야 하나 싶은 생각도 들었습니다.

제민님은 어떻게 처리하시는지 궁금합니다.

## 예외처리에 관해서 궁금한 점이 있습니다.

현재 저는

어떤 도메인.java
```
void addCount(){
 if(count==Integer.MAX_VALUE) throw new CustomException("더 이상 셀 수 없습니다.");
count++;
}
```
도메인 영역에 나온 메세지를 ExceptionHandler로 잡아서 그것을 그대로 응답으로 전달하고 있습니다.

최근 읽은 블로그에서는 예외 메세지는 프레젠테이션 계층의 책임이라는 문구를 읽었습니다. 그래서 도메인 영역이 예외메세지가 너무 강한 결합이 되어 있는가 라는 의문이 들었습니다. 

제민님은 어떻게 처리하고 계시는지 궁금합니다.

  
## 리팩토링 시점이 궁금합니다.

어떤 도메인1.java
```
// 200줄이 넘어가는 필드와 메소드

```
어떤 도메인2.java

```
UserId id;
UserName userName;
UserPhoneNumber userPhoneNumber;
```
어떤 도메인3.java
```
Long id;
String userName;
String userPhoneNumber;
```
리팩토링의 적정선을 정확히 모르겠습니다.
어떤 도메인1.java은 책임을 너무 많이 맡아서 분리 해야한다고 생각합니다. 하지만 어떤 도메인2.java는 너무 과한거 아닌가라는 생각이 합니다.
어떤 도메인3 처럼 해도 되지 않을까 라는 생각도 듭니다.

제민님의 기준과 생각이 궁금합니다.

##  맺음말
영상 기다리고 있겠습니다.

영상 열심히 보고 있습니다. 항상 좋은 영상 만들어주시고, 좋은 정보를 공유해주셔서 감사합니다.

**Comment by geminiKim** [comment]
질문 감사합니다! 추후에 영상으로 다뤄보겠습니다!

**Comment by geminiKim** [comment]
to: https://www.youtube.com/watch?v=SGVegQ4QXSY
