### ISSUE TITLE
[질문] 어떻게 하면 유지보수가 조금 더 편한 구조로 만들 수 있을까요 ?

### ISSUE THREAD

**Issue by zz9z9** [geminiKim/development-practice#64]
재민님 안녕하세요 ~ 재민님 유튜브 보면서 많이 배우고 있는 현업 개발자입니다.
제가 맡게된 서비스에서 요구사항을 처리하려고 하는데, 처리 자체는 어렵지 않지만 파악하고 변경하는데 너무 비효율적이라는 생각이 들어서요.
이 부분을 어떻게 개선하면 좋을지 잘 생각이나지 않아 고민해본 부분을 말씀드리고 재민님 의견도 들을 수 있으면 너무 좋을 것 같아 이렇게 질문올리게 되었습니다.
사실 재민님이 보시기엔 모듈 구조나 이런것부터 뜯어고칠 부분이 많다고 생각하실 것 같은데 어떤 피드백이라도 가감없이 주시면 감사하겠습니다 !

### 요구사항
> (실사례를 들고오긴 어려워서 각색한 내용입니다)
> - 기존에는 카드 단말기 번호에 대해 중복 허용이되지 않았는데, 이제는 카드 단말기 번호가 같더라도 단말기 브랜드가 다르면 등록될 수 있게 해주세요.
> - 즉, 단말기 테이블(`device_tbl`)의 PK가 `단말기 번호`에서 `단말기 번호, 단말기 브랜드`로 변경되는 상황입니다.

### 프로젝트 모듈 구성
```
- parent
 ㄴapi
 ㄴadmin
 ㄴbatch
 ㄴcore
```

### 내부 상황
- 단말기 등록 처리를 위해 단말기 번호로 조회 후 조회되는 단말기가 있으면 중복으로 간주, 없으면 등록 처리
- 단말기 등록 처리하는 로직이 여러 곳에서 필요함
  - admin : 여러 화면 (단말기 등록만 처리하는 화면, 다른 부분 처리하면서 단말기 등록도 처리되는 화면 등)
  - api : 외부에 노출된 여러 api
- spring-boot, mybatis 사용중 (Dao는 core가 아닌 각 모듈에 속해있음)

```java
// 매퍼 인터페이스
public interface AADao {
	단말기 selectDevice(Long 단말기번호);
	int insertDevice(Device device);
}
```

```java
// 매퍼 인터페이스
public interface BBDao {
	int selectDeviceCount(Long 단말기번호);
}
```

```java
@Service
public class DeviceServiceImpl implements DeviceService {
	public void createDevice() {
    	AADao.selectDevice; // 단말기 중복검사
        AADao.insertDevice; // 단말기 등록
    }
}
```

```java
@Service
public class StoreServiceImpl implements StoreService {
	public void createStore() {
    	// 가게 정보 저장
        BBDao.selectDeviceCount; // 단말기 중복 검사
        AADao.insertDevice // 단말기 등록
    }
}
```

- 따라서 이런 부분을 모두 `단말기 번호 & 브랜드`로 중복검사되도록 변경해야하는 상황

### 현재 상황에서 생각나는 작업 방식
  - PK 변경될 테이블명(`device_tbl`)으로 검색해서 관련된 쿼리 매퍼 파일(.xml) 찾는다.
  - 해당 매퍼 파일에 바인딩된 Dao를 찾는다.
  - 찾아낸 Dao들에서 `단말기 번호`로만 select 하는 부분을 호출하는 서비스 컴포넌트를 찾고 중복검사 후 insert까지 하는지 확인한다.
  - 해당 부분들을 다 수정해준다.

### 유지보수하기 좋지 않다고(변경하는데 시간 오래 걸린다고) 생각하는 이유
  - 결국 호출하는쪽(서비스 레이어)에서 하려는건 "단말기 등록"인데, 이를 위해서 단말기 중복여부를 검사해야하고 검사를 위해서는 `단말기번호`가 필요하다는걸 호출하는 쪽에서 다 알고있다.
    - 따라서, 중복여부 검사 로직이 변경되면 내부(즉, `단말기번호`가 필요하다는 것)를 알고 있는 로직들은 다 영향을 받는다.
  - 관련된 코드가 응집되어있지 않다. (AADao, BBDao 등에 분산)

### 생각해본 개선 방안 1
  - core에 단말기 등록을 관리하는 공통 서비스 만들기
     - 단말기 등록 처리는 해당 서비스에서만 처리하도록
     - 호출하는 쪽에서는 단말기 객체만 만들어서 넘기도록
  - 드는 생각
     - core에 들어가면 이 컴포넌트가 필요없는 batch 모듈에서도 불필요한 의존을 갖게되지 않나?
     - 만약 이러한 내용을 모르는 사람이 새로운 기능을 개발하다가 단말기 등록하는 부분을 처리해야할 때 `DeviceCoreServiceImpl`을 호출할 것이라는 보장이 없지 않나?
     - 만약, admin에서 해당 기능을 사용안한다고 하면, api 모듈 내부로 다시 옮겨야하는 것인가 ? 그러다 다른 모듈에서 사용한다고 하면 다시 core로 ?

```java
@Service
public class DeviceCoreServiceImpl implements DeviceCoreService {
	public void create(Device d) {
    	// 중복검사
        // 단말기 저장
    }
}
```

### 생각해본 개선 방안 2
  - jpa 사용
    - `device_tbl`에 맵핑되는 jpa entity에서 처리하면 변경 영향도가 적지 않을까?
    - 또한, jpa를 사용하면  어떤 사람이 새로운 로직을 개발할 때, 단말기 처리 기능이 필요한 경우 관련 테이블과 맵핑되는 entity는 무조건 확인하지 않을까? 하는 생각.. 
  - 드는 생각
     - 이것도 마찬가지로 core에 있게되면, 이 엔티티가 필요하지 않은 모듈에서는 불필요한 의존이 발생하는 것 아닌지 .. ?
     - 엔티티와는 별개로 개념 객체가 따로 있는 경우엔 어디서 처리하면 좋을까 ??
```java
@Entity
@Table(name = "device_tbl")
public class Device {
        public void create() {
            // 중복검사
            // 단말기 정보 리턴
        }
}
```

장황하게 긴 글 읽어주셔서 감사합니다 !

**Comment by geminiKim** [comment]
to: https://youtu.be/eOvfmo2p-74?si=RcLqz9mji_3pC9qC
