### ISSUE TITLE
[질문] 도메인 로직과 불필요한 DB 조회

### ISSUE THREAD

**Issue by cofires** [geminiKim/development-practice#65]
안녕하세요. 유튜브를 통해 많이 배우고 있습니다. 감사합니다. 

고민이 되는게 있어서 제미니님의 의견을 얻을 수 있을까 하고 질문 남깁니다. 

예시
- 채널, 유저, 구독정보 세가지가 존재합니다. 
- 채널이 **공개** 상태이면 어떤 유저든 접근이 가능합니다
- 채널이 **비공개** 상태이면 유저가 **시스템 관리자** 이거나 **채널의 구독자**여야 접근이 가능합니다.
- 접근 불가능할 경우 403 에러를 반환합니다.

이때 채널정보를 조회할때 조회할수 있는지에 대한 검증 로직을 짜려고 할때 두가지 방식중 어떤게 나은지 모르겠습니다. 제미니님의 생각을 듣고싶습니다.

첫번째 방법은 조회가능 여부를 알기위해 필요한 도메인 객체를 모두 로드한뒤에 검증합니다.
```js
function getChannel(channelId, loginUser){
    const channel = channelReader.findById(channelId)
    const user = userReader.findById(loginUser.id)
    const isSubscribed = subscribeReader.find(channelId,loginUser.id)
    
    channel.canAccess(user,isSubscribed)
    return channel
}

//Channel
function canAccess(user, isSubscribed){
    if (isPublic()) return true
    //... 로직 ...
}

```
---
두번째 방법은 필요할때마다 DB로부터 조회하는 방식입니다. channel이 공개라면 user 정보는 DB에서 가져올필요가 없으며, user가 관리자라면 구독여부도 가져올 필요가 없기 때문에 불필요한 DB조회를 줄인 방식입니다.

```js

function getChannel(channelId, loginUser){
    const channel = channelReader.findById(channelId)
    if (channelAccessManager.canAccess(channel,loginUser)){
        return channel 
    }else{
        // throw 403
    }
}

//channelAccessManager
function canAccess(channel,loginUser){
    if(channel.isPublic) return true

    const user = userReader.findById(loginUser.id)
    if (user.isAdmin()) return true
    const isSubscribed = subscribeReader.find(channelId,loginUser.id)
    if (isSubscribed) return true
    return false
}

```
제가 생각한 장단점입니다.
첫번째 구현방식
장점
- 접근검증로직 테스트하기 좋은것같습니다.
- DB조회와 검증로직이 분리됩니다.

단점
- 대신 실질적으로 불필요 DB 조회가 발생합니다.(유저와, 구독정보가 실질적으로 필요하지 않을때도 조회)

두번째 구현방식
장점
- 대신 효율적으로 DB조회가 가능합니다.(유저와 구독정보를 필요할때만 조회)

단점
- DB 조회와 검증로직이 섞여있습니다.
- userReader나 subscribeReader를 모킹해야해 비교적 테스트가 불편할거같습니다. 

감사합니다!

**Comment by geminiKim** [comment]
to: https://youtu.be/G2FXSpqcXa0?si=JZuDLtMT6q8U0EUN
