### ISSUE TITLE
[질문] 많은 엔티티들을 한번에 조회해야하는 경우

### ISSUE THREAD

**Issue by hong-sile** [geminiKim/development-practice#66]
[my 개념 지옥](https://www.youtube.com/watch?v=-3Wp_KGdnk8&pp=ygUg7KCc66-464uIIOqwnOuwnOyLpOustCBteSDsp4DsmKU%3D)
my개념에 대해 고민하고 있는 주제였는데, 잘 정리해주셔서 감사합니다!! 늘 재밌게 보고 도움을 받고 있어요!

사실 유사한 고민을 하나 하고있는게 있어요.

개발을 하다보면 프론트에게 "/my" api path로 프로필 화면을 구현하는 경우가 생기는데요.
(커머스를 예시로 들어볼게요)

유저의 orders, 유저의 products, 유저의 무언가 등등 ...

상당히 많은 엔티티들을 한번에 조회해야하는 요구사항들이 생기더라고요.
(굳이 my뿐만이 아니더라도, 상당히 많은 엔티티들을 한번에 다 조회해야하는 상황은 종종 생겼습니다. /main 같은 것도...)

이전에 아무생각 없이 짰을 때는 user 패키지에서 해당 요구사항을 처리했는데, user패키지가 해당 요구사항 하나 때문에 거의 대부분의 패키지에 의존하는 상황이 생기더라고요.

이런 의존을 해결하기 위해 "프로필 조회"와 같은 API에선 다수의 엔티티를 조회하기만 하는 용도로 별도의 도메인 패키지를 파고있는 것을 고려하고 있습니다.
(이 방법을 아직 프로젝트에서 시도해보진 않았습니다.)

이런경우 어떤식으로 처리하는 게 좋을까요?

패키지구조는 도메인인 경우입니다!!
```
user
    ㄴ application
    ㄴ domain
    ㄴ controller
order
    ㄴ application
    ㄴ domain
    ㄴ controller
etc...
```

1. 프론트에게 API를 분리하여 호출하라고 한다.
/my/orders -> order 패키지
/my/products -> product 패키지
/my/{domain} -> {domain} 패키지 etc...

장점 : 화면이 변하더라도 API가 변할 가능성은 낮아진다.
단점 : API 호출횟수가 많아진다, 프론트를 설득해야한다(?), 변경 시에 예상치 못한 side effect 가 많아진다.

여기서 말하는 side effect에 대해서 조금 더 부연설명을 하자면 다음과 같은 상황을 말하는 것이에요.

프론트가 프로필 페이지를 구성할 때도 /my/orders를 사용하고 있고, 자신의 주문목록만을 볼 때도 /my/orders를 사용하고 있는 상황입니다.

이 때, 나의 주문목록 화면이 변경되어서 /my/orders API의 필드가 추가/삭제/변경되는 경우, 이 여파가 프로필 페이지까지 전파되는 상황을 이야기하고 싶었어요.

단순히 웹 환경이라면 뭐 값이 잠시 null이 되는 정도겠지만 안드로이드의 경우엔 응답이 동일하지 않으면 에러를 발생시키기 때문에 문제가 생길 요소가 있다고 생각합니다.

프론트 측에서 호출하는 API들을 매번 다 고려하며 백엔드에 변경을 요청하는 것은 힘들 것 같아서요.

2. 프로필을 조회하는 별도의 패키지(profile?, readOnly?)를 만들고 /my 와 같은 API를 통해 요청하도록 한다.
//어떤 패키지 명이 적절한지 모르겠네요. 그래서 이게 맞는 방향인지 모르겠습니다.

장점 : 한방에 깔끔하게 해결된다. 한 화면만을 위한 API라 쓰이는 곳이 명확하기에 side effect가 발생하지 않는다. 오히려 유지보수면에선 이 방법이 더 나을 수도 있을 것 같다.
단점 : 화면에 엄청 의존적인 API, 의미가 크지 않은 조회만을 위한 패키지 생성

저는 처음엔 1번 방식이 낫다고 생각했다가 유지보수를 생각하니 2번이 더 끌리더라고요.
근데 또, 2번처럼 구성하다보면 모든 곳에 다 접근할 수 있는 패키지가 되다보니 어떻게 의존관계를 설정해야할지 감이 안 옵니다.

지금의 생각으론 별도의 통합 조회용 패키지를 파고, 데이터베이스에 조회만 하는 책임을 가진 domainService들(userRedader, orderReader, etc..)에 대해서만 의존하도록 하는 게 개발측면에선 더 나을 것 같습니다.

어떤 방법을 택하는게 더 나을까요?? 또 실무에선 이런 경우를 도메인 패키지 구조에서 어떻게 풀어가시나요?

긴 질문 읽어주셔서 감사합니다. 원래 댓글로 질문하려했는데 너무 길어져서 이슈로 물어봐요!!

**Comment by geminiKim** [comment]
to: https://youtu.be/7pOWbjZuirw?si=l33ZMEdlC6Wa6Tgf
