### ISSUE TITLE
[질문] 서비스 혹은 구현 계층에서의 예외 처리 전략과 모듈 간 상하관계

### ISSUE THREAD

**Issue by JinYongGo** [geminiKim/development-practice#72]
안녕하세요, 항상 유튜브 영상 재밌게 보고 있습니다!

다름이 아니라 API에서 예외 처리 전략에 대해 궁금한 점이 있어 질문 드립니다.

일반적으로 스프링 부트를 사용할 경우에 발생한 예외는 ControllerAdvice에서 처리하는데, 프레젠테이션-서비스-구현-외부(DB 등) 계층 구조를 가질 경우 예외를 서비스나 구현 계층 중 어디에서 발생시키는지 궁금합니다.

예를 들어 상품 주문을 했을 때 재고가 없다면 예를 들어 ProductNotRemainException 같은 예외를 발생시키고 이를 ControllerAdvice에서 처리할텐데, 해당 예외는 구현 계층(예를 들어 ProductManager)에서 발생시키는게 좋을까요?

그리고 예를 들어 게시글 도메인과 유저 도메인이 있을 때, 도메인 간 상하 관계(위상)은 게시글 > 유저로 설계하는게 맞을 것 같은데 그런 경우 모듈 간 의존 관계 설정은 어떻게 하는게 맞을까요?

예를 들어 core-api에서는 유저 도메인과 게시글 도메인을 모두 참조하고 있고, 게시글 도메인에서는 유저 도메인을 참조하고 있다면 게시글 도메인에서는 compileOnly로 유저 도메인을 참조하는게 좋을지 제미니님 의견이 궁금합니다.

항상 영상 유익하게 보고 있고, 의견을 주시면 감사하겠습니다!

**Comment by geminiKim** [comment]
> 일반적으로 스프링 부트를 사용할 경우에 발생한 예외는 ControllerAdvice에서 처리하는데, 프레젠테이션-서비스-구현-외부(DB 등) 계층 구조를 가질 경우 예외를 서비스나 구현 계층 중 어디에서 발생시키는지 궁금합니다.

계층별 예외에 대학 책임이 약간씩 다를 수 있습니다.
- 프레젠테이션 = 외부 요청에 대한 예외를 발생
- 비즈니스 = 비즈니스 적인 흐름 처리 시 예외를 발생
- 임플먼트(구현) = 구현 처리 시 예외를 발생
- 데이터 액세스 = 데이터 처리 시 예외를 발생

> 예를 들어 상품 주문을 했을 때 재고가 없다면 예를 들어 ProductNotRemainException 같은 예외를 발생시키고 이를 ControllerAdvice에서 처리할텐데, 해당 예외는 구현 계층(예를 들어 ProductManager)에서 발생시키는게 좋을까요?

전체 비즈니스와 구현 상황을 봐야하고, 케이스마다 다르지만 해당 예시에서는 재고를 직접적으로 관리하는 구현 계층에서 처리하는게 적절해보입니다.

> 그리고 예를 들어 게시글 도메인과 유저 도메인이 있을 때, 도메인 간 상하 관계(위상)은 게시글 > 유저로 설계하는게 맞을 것 같은데 그런 경우 모듈 간 의존 관계 설정은 어떻게 하는게 맞을까요?

이것 또한 비즈니스와 케이스를 보셔야하지만, 잘 생각해보시면 유저와 게시글 사이의 `관계` 는 밀접하지 않아야하고 `위상` 의 차이는 없어야하는게 일반적 같습니다.

게시글에서 유저를 직접적으로 써야하는 이유가 있을까요? 대부분의 경우는 게시글에서 유저는 `작성자ID` 정도로만 국한 되면 충분한 것 같습니다.

그런 의미에서 특히나 범용적인 `유저` 에 대한 의존 관계 설정이 없을 수 있다면 가장 좋습니다. (이건 제 영상 중 my 개념 관련 된 영상을 보시면 느끼실 수 있을 것 같아요)

이게 잘 못 퍼지다보면 유저는 어딜가나 혹 처럼 다 달려있고 전체 프로젝트 복잡도를 올릴 것 입니다.
그 부분은 프로젝트의 전체 상황을 잘 느끼시면서, 주의하시면 좋을 것 같아요


> 예를 들어 core-api에서는 유저 도메인과 게시글 도메인을 모두 참조하고 있고, 게시글 도메인에서는 유저 도메인을 참조하고 있다면 게시글 도메인에서는 compileOnly로 유저 도메인을 참조하는게 좋을지 제미니님 의견이 궁금합니다.

그럼에도 굳이 걸어야한다면 적어주신 형태가 맞을 것 같긴한데, 특별한 요구사항이나 이유가 있지 않다면 모듈 분리가 너무 과하게 느껴집니다.

전체 코드를 못 봐서 속단이지만, 게시글 자체가 모듈로 되어있다는 것도 너무 작은 응집을 갖고 있는 것 같아요.
