### ISSUE TITLE
[질문] 익셉션으로 비즈니스 로직 처리시 response와 request 클래스의 포맷

### ISSUE THREAD

**Issue by Bue-von-hon** [geminiKim/development-practice#73]
요약
- 서버쪽 정상/비정상 응답 클래스 형식이 다름(익셉션 핸들러와 서비스의 응답 클래스 포맷이 다름)
- 이때문에 클라이언트는 catch 구문안에서 비즈니스 처리

안녕하세요 제미니님. 🙂
저는 다른분이 개발한 서버 프로그램과 통신해야하는 클라이언트쪽 개발을 진행중인 개발자입니다.
최근 영상에 올리신 내용에 흥미로운 내용을 발견하여 질문을 남깁니다!

본문
도메인 익셉션과 어플리케이션 익셉션으로 나누어 진행하시네요.
익셉션으로 비즈니스 로직을 처리한다면, 메소드를 사용하는 클라이언트 코드에서는 catch 구문안에 비즈니스 로직이 들어가야하는거 아닌가요?

예를들어 비밀번호 input 박스에 값을 넣고 submit 버튼을 누르면, 서버에서 검증한다고 해보죠.
서버에서는 비밀번호가 스펙에 맞게 들어오면 정상 처리하지만 스펙에 맞지 않으면, 예를들어 너무 짧거나 특수문자등이 포함되지 않으면, RuntimeException을 던지는거죠.

스프링의 경우 익셉션 핸들러에서 이를 처리하게 되는데, 정상 응답과 익셉션 핸들러의 응답이 다른 형식이라면, 클라이언트는 catch를 이용해서 스펙에 맞지 않는 비밀번호에 대한 처리를 해야합니다.
왜냐하면 정상일때 내려오는 응답 클래스와 비정상일때 내려오는 응답 클래스가 다르기 때문입니다...

**Comment by geminiKim** [comment]
뭘 질문하시려는 건지 핵심을 잘 모르겠어요, 무슨 영상의 어느 부분을 보신 건가요?

> 서버쪽 정상/비정상 응답 클래스 형식이 다름(익셉션 핸들러와 서비스의 응답 클래스 포맷이 다름)

정상/비정상 시 동일한 클래스로 응답합니다, (익셉션 핸들러와 서비스의 응답 클래스가 같습니다)
ControllerAdvice 에서 예외를 받고 응답은 API 서버 표준 클래스로 동일한 형태로 응답합니다.

> 익셉션으로 비즈니스 로직을 처리한다면, 메소드를 사용하는 클라이언트 코드에서는 catch 구문안에 비즈니스 로직이 들어가야하는거 아닌가요?

익셉션으로 비즈니스 로직을 처리한다는 게 무슨 의미인지 모르겠습니다, 뒤에 내용도 정리가 명확하게 안된 질문 같아요.
요약을 봐도 질문의 핵심이 안보입니다 궁금한게 있다면 명확하게 정리해서 다시 물어봐주세요
