### ISSUE TITLE
[질문] 요청/응답 호환성

### ISSUE THREAD

**Issue by Bue-von-hon** [geminiKim/development-practice#74]
안녕하세요 제미니님
저는 모바일앱과 통신하는 서버 프로그램 개발중인 개발자입니다. (잡부입니다..🤣)
모바일앱은 한번 릴리즈 찍히면, 강업(강제 업데이트)하지 않는 이상 업데이트를 할 수 없는데요.
이 때문에 서버쪽에서는 이전 버전 요청 형식을 받았을때 처리를 고려하지 않으면 안되요...ㅠ
하지만 하위 호환성만 있는게 아니라... 상위 호환성도 문제예요
사실 저는 클라이언트쪽도 개발중인데, 반드시 서버 먼저 업데이트된다는 보장이 없기 때문이예요!
뒤죽박죽으로 업데이트되는 프로그램들과 문제없이 통신하려면 어떻게 해야할까요!

**Comment by geminiKim** [comment]
앱 하위호환 관련 얘기를 했던 영상이 있는데 어떤 영상인지 기억이 안나네요, 찾아보시면 나오긴 할 겁니다.

API 버전을 분리하시는 방안을 활용하시면 기본적인 하위/상위 호환에 대해서 어느정도 잘 대응하실 수 있을겁니다.
