### ISSUE TITLE
[질문] 특정 커밋을 제외하고 릴리즈한 이후 동기화 방법

### ISSUE THREAD

**Issue by Bue-von-hon** [geminiKim/development-practice#75]
브랜치에서 특정 커밋을 제외하고 릴리즈해야하는 경우가 있었습니다.
로컬에서 rebase를 이용해 특정 커밋을 drop 하고 원격에 force push해서 릴리즈갔습니다.
해당 브랜치에서 작업하던 다른 팀원들의 로컬에는 force push로 드랍한 커밋이 남아있어서, 제가 직접 자리에 찾아가서 rebase drop 작업을 했습니다.
(심지어 로컬에 해당 커밋이 남아계신 분들이 push하면, 문제되는 커밋이 딸려오고 있었습니다...)
수동으로 로컬-원격 동기화를 하지 않고, 자동화하고 싶은데 방법이 있나요?

p.s. 전에 질문을 잘 못해서 죄송합니다. 너무 궁금해서 마음이 앞섰습니다. 🙇🏻‍♂️

**Comment by geminiKim** [comment]
@Bue-von-hon 
보통 이런 경우라면 팀내 전파해서 remote 를 다시 땡겨오게하는게 일반적인 것 같아서, 팀내 깃 사용법을 잘 가이드해야하지 않나 싶습니다

- 상상해보면 develop 에 다 같이 공동작업을 하고 있는데
- master 를 가기전 빼야하는 커밋을 빼고, develop 에 force-push

이런 상황이면 다른 팀원 분들이 rebase drop 이 아니라 remote fetch 를 받고 reset hard 하면될 것 같습니다.
(작업 사항이 있다면 stash 에 넣어두고요)

--

자동화에 대해서는 저도 잘 모르지만 스크립트를 작성 할 수 있을 것 같은데, 이 케이스의 문제는 기본 사용법 측면이 더 커 보여서 근본을 고쳐야하지 않나 싶네요
