### ISSUE TITLE
[질문] 레이어 컨벤션 구축 방법이 있을까요??

### ISSUE THREAD

**Issue by vanillacake369** [geminiKim/development-practice#77]
안녕하세요~! 애청자이자 즐겨보고 있는 구독자입니다~!

두괄식으로 질문 드려보자면, 레이어를 분리할 때 효율적으로 관리하는 방법이 있을까요?

현재 저희 사내에서는 Service 간의 의존관계는 기피하고자하는 분위기라 계층식 단일의존성을 지향하고 있는데요.

다만 아키텍처에 대한 마땅한 코드컨벤션이 없어 아래 두 예시와 같은 코드가 작성됩니다.

```java
// 복합 로직 담긴 요구사항

@Slf4j
@Controller
@RequiredArgsConstructor
public class DomainCCreateController {

  private final DomainCCommandFacade domainCCommandFacade;

  ,,,
}

@Slf4j
@Component
@RequiredArgsConstructor
public class DomainCCommandFacadeImpl {

  private final DomainAQueryService domainAQueryService;
  private final DomainBQueryService domainBQueryService;
  private final DomainCCommandService domainCCommandService;

  ,,,
}
```

```java
// 간단한 조회 요구사항

@Slf4j
@Controller
@RequiredArgsConstructor
public class DomainDCreateController {

  private final DomainDQueryService domainDQueryService;

  ,,,
}

@Slf4j
@Component
@RequiredArgsConstructor
public class DomainDQueryServiceImpl {

  ,,,
}
```

보시다싶이 요구사항의 복잡도에 따라 레이어가 중구난방입니다.

즉, 복잡한 요구사항이라면 레이어가 추가되기도 했다가, 단순한 요구사항이라면 하나의 레이어에서 처리됩니다.

결과적으로 Service, Facade, Provider, Workflow 등등 여러 레이어들이 마구마구 생겨나고 있습니다.

이렇게 레이어들이 동적으로 늘었다 줄었다 하니, 이런 부수효과가 생기더라고요.

- 컴포넌트 생성 시 어떤 레이어에 두어야할지 모르게된다.
- 상이한 코드스타일에 따라 코드에 대한 이해도를 파악하기 위해 코드를 다시 훑어야한다.
- 어떤 레이어에서 어떤 레이어를 의존할지 파악이 어렵게 된다.
- 이름에 따라 레이어 구분이 거의 불가능하다.

혹시 이에 대해서 좋은 혜안이 있으실까요??

** 개인적인 사견으로, 계층식 단일의존성을 버리지 않는 이상, 정적인 레이어 계층 컨벤션을 수립하기가 어렵다고 생각합니다.

** 흑자는 "레이어 컨벤션보다 읽기 쉽기 수정하기 쉽게 개발한다면, 크게 문제가 없다" 는 의견도 있습니다.

**Comment by geminiKim** [comment]
to: https://youtu.be/RB6AI0OQWps?si=Y5ihEDBzMB2SxlkH
