### ISSUE TITLE
개념 간 순환참조 사례 살펴보기

### ISSUE THREAD

**Issue by geminiKim** [geminiKim/development-practice#82]
<img width="809" alt="스크린샷 2024-09-03 오후 2 39 12" src="https://github.com/user-attachments/assets/a62b5600-906b-4f20-89d6-a9a461495ea2">

코드 : https://gist.github.com/JiwonKKang/5a05ca752fba37b54836d62c624c9de2

**Comment by JiwonKKang** [comment]
답변 정말 감사합니다. 영상으로 얘기해주신다니 영광입니다....
그렇다면 혹시 "격벽"을 뛰어넘어 참조할 경우에 발생할수있는 문제점에 대해서도 간단하게 설명해주신다면 정말 감사하겠습니다!!

**Comment by geminiKim** [comment]
@JiwonKKang 영상 촬영을 했는데 추가 댓글 답을 못 드려서 댓글로 남겨둡니다

격벽을 뛰어넘어 참조할 경우 당장 문제 자체는 발생하지 않습니다.

다만 격벽을 무분별하게, 너무 쉽게 넘어다닐 경우 결국 격벽이 없는 것 처럼 통제가 없는 상태가 되므로 예기치 못한 코드의 오염이 퍼지고, 유지보수성 생산성 확장성의 문제가 생길 수 있다는게 문제라고 생각하시면 좋을 것 같습니다

그리고 가장 큰 문제는 문제를 발견하는 시점엔 이미 수술이 필요한 상황이 대다수이라는 것 같습니다, 그러므로 꾸준히 개념이 너무 과하게 벽을 넘나들지 않는지 체크가 필요합니다

**Comment by geminiKim** [comment]
to: https://youtu.be/q_jXsdRnPL4?si=lPL8o-TOmV_V4eHM
