### ISSUE TITLE
[질문] 경품 추천 이벤트 서비스 시스템 설계 궁금한 점

### ISSUE THREAD

**Issue by rlaope** [geminiKim/development-practice#92]
안녕하세요! 좋은 영상 항상 잘 보고있는 구독자입니다.

최근에 이벤트성 프로젝트를 기획하고 있어서, 다양한 상황을 고려하고있는데, 자세히는 말씀 못해드리고 예를 들어서 설명해봤을때 이 상황에서 어떻게 설계하면 좋을지 어떤 부분을 고려하면 좋을지에 대해서 설명해주실 수 있을지 질문 드립니다.

웹페이지에서 유저 유입을 위해서 경품 당첨 이벤트를 하려고 합니다.
버튼을 누른 사람중에 10만번째 누른 사람(유저는 이 기준을 모름)에게 상품을 준다했을때 
오후 7시 부터 버튼을 누를 수 있고 바로 당첨 여부를 확인할 수 있습니다. 이러한 시스템을 설계한다고 했을때

만약 트래픽이 초당 10만까지도 발생할 수 있다고 가정하고 (100만이 될 수도 있고 ... ) 시스템을 설계한다면
스케일링 뿐만 아니라 다양한 측면으로. 데이터 일관성이라던지 부하 감당 등등 방안?
이 부분에 대해서 고려해야할 점, 구현 방안이나 경험에 근거한 다양한 솔루션? 등을 알려주실 수 있는지 요청해봅니다. 감사합니다!

**Comment by geminiKim** [comment]
유튜브 댓글에 답변드렸습니다.
from: https://www.youtube.com/watch?v=xArEmJXvsyA
--
음..적어주신 내용 대비 너무 폭 넓은 범위의 질문이네요
이벤트 같은 경우는 상황별로 정말 다양한 구현과 설계를 할 수 있습니다.

우선 빠르게 작업 후 성능테스트에서 10만+@ 트래픽을 붓고 그 이상으로 올려보면서, 문제를 먼저 찾고 고민 해보셔도 늦지 않을 것 같습니다.

트래픽 가정을 10만 ~ 100만으로 대략 적어주셨는데요, 이런 식으로 폭이 크게 접근하면 오버 엔지니어링을 하기 쉽습니다.
현실적인 트래픽 수치부터 정해보시고, 거기에 3배 정도를 받는다고 고려해 보시길 추천드립니다.

댓글에 적어주신 대로 '다양한 측면'을 검토해야 합니다. 그러고 더 효율적인 방안은 현재 방안의 문제점이 나오고 고민해도 늦지 않습니다.
빠르게 구현해서 빠르게 성능 테스트로 피드백 루프를 구축해서 반복할 준비가 되시면 좋을 것 같습니다.

그렇게 해보시고 모호한 부분이 있다면 범위를 좁혀서 질문 주시면 제 의견을 말씀해 드릴 수 있을 것 같습니다.
