### ISSUE TITLE
[질문] JPA를 통한 프로젝트를 진행하던 중 복합키로 변경했을 때 대응방법이 궁금합니다.

### ISSUE THREAD

**Issue by qkrxodud** [geminiKim/development-practice#96]
안녕하세요.
기존에 프로젝트를 하던 중 신규 프로젝트가 들어와서 개발을 진행하게 되었습니다.
신규 프로젝트는 성공적으로 마무리하였는데요.

과거 프로젝트에 중복 데이터가 생성되어 문제를 확인하였는데 프로젝트 전반에 큰 영향이 있어서 고민이 됩니다.
기존 테이블에 id를 Long 타입으로 선언하고 사용하고 JPA에서도 @Id @GeneratedValue(strategy = GenerationType.IDENTITY)로 사용 중에 있었습니다.
그러던 중 제가 신규 프로젝트를 진행하고 있을 때, 파티셔닝을 진행한다고 테이블의 key를 복합키로 변경하였습니다.(Id + createdAt)으로 JPA에서는 @GeneratedValue(strategy = GenerationType.IDENTITY)
를 삭제하고 @Id로 사용하고 있었습니다.

문제는 기존에 소스코드에서 findById, exesist 등 Key로 조회하는 부분을 (@IdClass 또는 @EmbeddedId 어노테이션 사용)을 수정하지 않고 바로 적용했다는 것입니다.
이로 인해 findAllById을 할 경우 3개의 데이터가 DB에서는 다르지만, Entitiy로 변경하는 순간 같은 데이터가 3개가 노출이 되고 있습니다. key로 사용하고 있는 함수들이 많이 있는데,, 전부 수정하기도 힘들고 제일 큰 문제는 조회를 하기 위해서 사용자가 CreatedAt을 알고 있어야 된다는 점입니다. 이런 문제가 발생되었을 때 어떻게 대응하는지 궁금하여 글 남기게 되었습니다.
감사합니다.

——
요약
기존 상태
* 초기 프로젝트: 단일 ID (Long 타입)
* JPA 설정: @GeneratedValue(strategy = GenerationType.IDENTITY)

변경된 상태
* 파티셔닝을 위해 복합키로 변경 (ID + 생성일시)
* JPA 설정: @GeneratedValue 삭제
* 조회 메서드(findById, exists 등) 수정 누락

현재 문제점
* DB에서는 3개의 다른 데이터를 조회후 엔티티로 변환 시 3개의 데이터가 동일하게 처리됨
* 존재하는지 체크하고 데이터를 save를 해야 되는데, 데이터를 확인함에도 불과하고 중복데이터가 생김.

**Comment by geminiKim** [comment]
문제 상태에 대해서는 본문에 이미 다 적혀있고, 알고 계신 것 같아서 어떤 걸 말씀드려야할지 모르겠네요.

`@IdClass` 또는 `@EmbeddedId` 를 사용하게 바꾸시고
조회하는 영역을 모두 파티션키 기반으로 조회하도록 변경 하셔야 할 것 같습니다.

그리고 createdAt 으로 파티셔닝을 걸게 되면 유연성이 떨어지는 것 같습니다
파티셔닝 단위를 어떻게 거셨는지 모르겠지만 검색 조건으로 사용시 상당히 애매할 것 같습니다. 
(일시가 붙어있기 때문에 계속 날짜 범위로 조회 해야할듯하네요)

전반적으로 파티셔닝 관련하여서 학습 및 전략에 대한 고민을 더 해보셔야할 것 같습니다.

**Comment by qkrxodud** [comment]
안녕하세요.
개발 기간이 있다 보니 엔티티로 변환하지 않고 Object로 변환해서 일단 개발은 완료하였고,
전달 주신 내용처럼 CreatedAt이 아닌 다른 것으로 파티셔닝을 변경하는 것을 고려하고 있는 중입니다.

어떤 방향성이 맞을까 고민하여 글 올리게 되었는데, 답변 주셔서 감사합니다.

——
요약:
- 개발 기간의 제약으로 인해 엔티티 대신 Object로 변환하여 개발을 완료했음
- CreatedAt이 아닌 다른 방식으로 파티셔닝을 변경하는 것을 검토 중
