### ISSUE TITLE
[질문] JPA를 써야 하는지에 대한 질문입니다

### ISSUE THREAD

**Issue by gyungjae-ham** [geminiKim/development-practice#97]
### 궁금해진 이유
1. 지금 멀티 모듈 구조에 따르면, 영속성 객체는 persistence layer를 나갈 수 없습니다.
  - domain layer에서 interface를 persistence가 의존하면서 구현하고 있기 때문입니다.
2. 그렇다면 영속성 테이블 관리 등의 리소스를 써야 할 이유가 있을까?

### 생각이 진행된 이유
1. 원래부터 위 생각을 하고 있었습니다.
2. 최근 querydsl 보안 이슈와 더불어서 이 라이브러리가 관리가 안된다고 느껴져서 대안으로 우선 옮겨갔으나 애초에 querydsl을 왜 쓰지라는 생각을 하게되었습니다
3. JPA 만으로 한계가 있어서 쓰고 있다는 걸 알게 되었고, ?? 굳이 쓸 구조가 아닌거 같은데 왜 Jdbc + jooq 같은 조합으로는 안쓰는걸까? 라는 생각에 질문드립니다

### 궁금한 점
1. 제미니님은 JPA를 쓰고 계시나요?
2. 만약 사용중이시라면 저런 모듈 구조에서 이점이 없다고 생각되는데 어떤 이점과 어떤 트레이드오프가 있어서 사용중이실까요?

**Comment by geminiKim** [comment]
(뭔가 자문자답하신 것 인지 몰라도 빨리 이슈를 닫으셨네요)
제 생각을 짧게 전달드리면 정확히 따지고 보면 모듈 구조랑 JPA랑 쓰는 것은 상관관계가 없는 것 같습니다.

오히려 구현이나 데이터를 다루는 패턴이 JPA가 반드시 필요하지 않은 이유가 많다면 굳이 JPA를 쓸 필요는 없다고 생각합니다.
팀에서 익숙하고 편한 구현체를 사용하는게 좋을 것 같습니다.
